import { defineConfig } from 'vite';
import { resolve } from 'path';
import { readdirSync, existsSync } from 'fs';

// `__dirname` is not defined under Vite's native config loader.
const root = import.meta.dirname;

// Blog pages are generated by scripts/build-blog.mjs before the build runs
// (see the `build` script in package.json), so they are discovered rather
// than listed by hand — adding a post to src/data/blog.js is enough.
function aboutInput() {
  const page = resolve(root, 'about/index.html');
  if (!existsSync(page)) {
    throw new Error(
      'vite.config.js: about/ is missing. Build with `npm run build` ' +
      '(which runs scripts/build-about.mjs first), not `vite build` on its own.'
    );
  }
  return page;
}

function blogInputs() {
  const dir = resolve(root, 'blog');

  // The blog is generated by scripts/build-blog.mjs, which `npm run build`
  // runs first. If something bypasses that step the pages simply would not
  // exist and the build would quietly succeed without them, so stop here
  // rather than shipping a site whose /blog routes 404.
  if (!existsSync(dir)) {
    throw new Error(
      'vite.config.js: blog/ is missing. Build with `npm run build` ' +
      '(which runs scripts/build-blog.mjs first), not `vite build` on its own.'
    );
  }

  const inputs = { blogIndex: resolve(dir, 'index.html') };
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const page = resolve(dir, entry.name, 'index.html');
    if (existsSync(page)) inputs[`blog_${entry.name.replace(/-/g, '_')}`] = page;
  }
  return inputs;
}

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(root, 'index.html'),
        work: resolve(root, 'work.html'),
        // Dedicated Case Studies
        auricJewels: resolve(root, 'work/auric-jewels.html'),
        gemhub: resolve(root, 'work/gemhub.html'),
        kisaansay: resolve(root, 'work/kisaansay.html'),
        superup: resolve(root, 'work/superup-home-solution.html'),
        kabeer: resolve(root, 'work/kabeer-confectionery.html'),
        vedaClub: resolve(root, 'work/veda-club.html'),
        akiso: resolve(root, 'work/akiso.html'),
        rupeenest: resolve(root, 'work/rupeenest-capital.html'),
        // Service Pages
        brandStrategy: resolve(root, 'services/brand-strategy.html'),
        brandIdentity: resolve(root, 'services/brand-identity.html'),
        creativeContent: resolve(root, 'services/creative-content.html'),
        digitalMarketing: resolve(root, 'services/digital-marketing.html'),
        performanceMarketing: resolve(root, 'services/performance-marketing.html'),
        webDevelopment: resolve(root, 'services/web-development.html'),
        // Generated pages — see the build script in package.json
        about: aboutInput(),
        ...blogInputs(),
      },
    },
  },
});
